baseURL = "http://mcoo.me/" # The URL of your site.
title = "鱼摆摆" # Title of your site
theme = "鱼摆摆" # Name of Zzo theme folder in `themes/`.
subtitle = "The world’s fastest framework for building websites"

defaultContentLanguage = "en" # Default language to use (if you setup multilingual support)
defaultContentLanguageInSubdir = true # baseURL/en/, baseURL/kr/ ...
hasCJKLanguage = true # Set `true` for Chinese/Japanese/Korean languages.

summaryLength = 70

copyright = "&copy;{year}, All Rights Reserved" # copyright symbol: $copy; current year: {year}
timeout = 10000
enableEmoji = true
paginate = 13 # Number of items per page in paginated lists.
rssLimit = 100

pygmentsOptions = "linenos=table"
pygmentsUseClasses = true

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[outputs]
  home = ["HTML", "RSS", "JSON", "WebAppManifest"]

[mediaTypes."application/manifest+json"]
  suffixes = ["webmanifest"]

[outputFormats.WebAppManifest]
  mediaType = "application/manifest+json"
  rel = "manifest"

[taxonomies]
  category = "categories"
  tag = "tags"
  series = "series"