[[main]]
  identifier = "about"
  name = "about"
  url = "about"
  weight = 1

[[main]]
  identifier = "Linux"
  name = "Linux"
  url = "categories/linux"
  weight = 2
  
  [[main]]
  identifier = "Redis"
  name = "Redis"
  url = "categories/Redis"
  weight = 3

[[main]]
  identifier = "archive"
  name = "archive"
  url = "archive"
  weight = 5

[[main]]
  identifier = "gallery"
  name = "gallery"
  url = "gallery"
  weight = 3
    
[[main]]
  parent = "gallery"
  name = "cartoon"
  url = "gallery/cartoon"

[[main]]
  parent = "gallery"
  name = "photo"
  url = "gallery/photo"

[[main]]
  identifier = "posts"
  name = "posts"
  url = "posts"
  weight = 4
    
[[main]]
  identifier = "notes"
  name = "notes"
  url = "notes"
  weight = 5